# Reference:
#   https://github.com/koki-develop/git-aicommit/blob/main/.github/workflows/release-please.yml
name: Release Please

on:
  push:
    branches:
      - main

concurrency:
  group: release-please
  cancel-in-progress: false

env:
  UV_CACHE_DIR: /tmp/.uv-cache
  APP_NAME: sync_var

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      should-publish: ${{ steps.release-please.outputs.release_created }}
      tag: ${{ steps.release-please.outputs.tag_name }}
    steps:
      - uses: actions/create-github-app-token@v2.2.0
        id: app-token
        with:
          app-id: ${{ secrets.RELEASE_PLEASE_APP_ID }}
          private-key: ${{ secrets.RELEASE_PLEASE_APP_PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: write
      - uses: googleapis/release-please-action@v4.4.0
        id: release-please
        with:
          token: ${{ steps.app-token.outputs.token }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

  publish:
    name: Publish
    needs: release-please
    if: needs.release-please.outputs.should-publish == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write # for gh release upload
    steps:
      - uses: actions/checkout@v6.0.0
        with:
          persist-credentials: false
      - uses: jdx/mise-action@v3.5.0
      - uses: actions/cache@v4.3.0
        with:
          path: ${{ env.UV_CACHE_DIR }}
          key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
            uv-${{ runner.os }}

      - run: uv sync --locked --all-extras --dev
      - run: uv build --verbose
      - run: uv cache prune --ci
      - run: gh release upload "${TAG_NAME}" dist/${APP_NAME}-* --clobber
        env:
          GH_TOKEN: ${{ github.token }}
          TAG_NAME: ${{ needs.release-please.outputs.tag }}
          APP_NAME: ${{ env.APP_NAME }}
